configVersion: 1.0.0
componentName: tcpip_driver_config
coreVersion: 5.8.2
device: ATSAME54P20A
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: tcpip_driver_config
  type: module
  version: ''
- dependencyPackage: ''
  name: net
  type: package
  version: v3.11.0
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments: {}
  elementPosition:
    attributes:
      id: DRIVER LAYER
    children:
    - children:
      - attributes:
          id: tcpip_driver_config
          x: '20'
          y: '19'
        type: ElementPosition
      type: ElementPositions
    type: ComponentGraph
  symbols:
    TCPIP_AUTOCONFIG_ENABLE_ENCX24J600:
      attributes:
        id: TCPIP_AUTOCONFIG_ENABLE_ENCX24J600
      children:
      - children:
        - attributes:
            value: 'true'
          type: User
        type: Values
      type: Boolean
    TCPIP_AUTOCONFIG_ENABLE_GMAC:
      attributes:
        id: TCPIP_AUTOCONFIG_ENABLE_GMAC
      children:
      - children:
        - attributes:
            value: 'true'
          type: User
        type: Values
      type: Boolean
    TCPIP_AUTOCONFIG_ENABLE_KSZ8091:
      attributes:
        id: TCPIP_AUTOCONFIG_ENABLE_KSZ8091
      children:
      - children:
        - attributes:
            value: 'true'
          type: User
        type: Values
      type: Boolean
    TCPIP_AUTOCONFIG_ENABLE_MIIM_Driver:
      attributes:
        id: TCPIP_AUTOCONFIG_ENABLE_MIIM_Driver
      children:
      - children:
        - attributes:
            id: tcpip_driver_config
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
  userData: {}
