configVersion: 1.0.0
componentName: tcpip_network_config
coreVersion: 5.8.2
device: ATSAME54P20A
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: tcpip_network_config
  type: module
  version: ''
- dependencyPackage: ''
  name: net
  type: package
  version: v3.11.0
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments: {}
  elementPosition:
    attributes:
      id: NETWORK LAYER
    children:
    - children:
      - attributes:
          id: tcpip_network_config
          x: '20'
          y: '20'
        type: ElementPosition
      type: ElementPositions
    type: ComponentGraph
  symbols:
    TCPIP_AUTOCONFIG_ENABLE_ARP:
      attributes:
        id: TCPIP_AUTOCONFIG_ENABLE_ARP
      children:
      - children:
        - attributes:
            id: tcpip_network_config
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    TCPIP_AUTOCONFIG_ENABLE_ICMPv4:
      attributes:
        id: TCPIP_AUTOCONFIG_ENABLE_ICMPv4
      children:
      - children:
        - attributes:
            value: 'true'
          type: User
        type: Values
      type: Boolean
    TCPIP_AUTOCONFIG_ENABLE_IPV4:
      attributes:
        id: TCPIP_AUTOCONFIG_ENABLE_IPV4
      children:
      - children:
        - attributes:
            id: tcpip_apps_config
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
  userData: {}
