configVersion: 1.0.0
componentName: BASIC CONFIGURATION
coreVersion: 5.8.2
device: ATSAME54P20A
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyGroupModule
  name: BASIC CONFIGURATION
  type: module
  version: ''
- dependencyPackage: ''
  name: CMSIS_5
  type: package
  version: 5.9.0
- dependencyPackage: ''
  name: bsp
  type: package
  version: v3.17.0
- dependencyPackage: ''
  name: core
  type: package
  version: v3.13.3
- dependencyPackage: ''
  name: crypto
  type: package
  version: v3.8.1
- dependencyPackage: ''
  name: csp
  type: package
  version: v3.18.2
- dependencyPackage: ''
  name: net
  type: package
  version: v3.11.0
- dependencyPackage: ''
  name: wolfssl
  type: package
  version: v5.4.0
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments:
    children:
    - children:
      - attributes:
          id: Core_SysConsole_Dependency
          namespace: tcpipStack
        type: Attachment
      - attributes:
          id: NETCONFIG_MAC_Dependency
          namespace: tcpipNetConfig_0
        type: Attachment
      type: Attachments
    type: BASIC CONFIGURATION
  elementPosition:
    attributes:
      id: TCP/IP STACK
    children:
    - children:
      - attributes:
          id: BASIC CONFIGURATION
          x: '423'
          y: '145'
        type: ElementPosition
      type: ElementPositions
    type: ComponentGraph
  symbols: {}
  userData: {}
