name: CI Test
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore Packages
      run: nuget restore WpfApp1.sln
    
    - name: Build solution
      run: msbuild WpfApp1.sln -t:rebuild -property:Configuration=Release
