name: CI Test
on:
  push:
    paths:
      - "Apps/Blind-Config-Tool"
    branches:
      - main
      
  pull_request:
      paths:
        - "Apps/Blind-Config-Tool"
      branches:
        - main


jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    
    - name: Restore Packages
      run: nuget restore "Apps/Blind-Config-Tool/Blind Config Tool.sln"
    
    - name: Build solution
      run: msbuild "Apps/Blind-Config-Tool/Blind Config Tool.sln" -t:rebuild -property:Configuration=Release
