name: Firmware CI

on:
  pull_request:
    paths:
      - 'Firmware/projects/**'
  push:
    paths:
      - 'Firmware/projects/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add the projects to perform CI to the matrix. 
        project:
          - fa_interface
          - fa_blind
          - mechanisms/PSE-Net

    steps:
      # Step 1: Checkout the repository. We need two commits to be able to determine what has changed.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Step 2: Determine if this matrix project has changes
      - name: Check if project changed
        id: check_project
        run: |
          # Use base_ref for PRs, or previous commit for push
          if [ -n "${{ github.base_ref }}" ]; then
            BASE=${{ github.base_ref }}
          else
            BASE=HEAD~1
          fi

          # If the git diff contains any of the projects in the matrix then append those to the output variable
          if git diff --name-only $BASE | grep -q "^Firmware/projects/${{ matrix.project }}/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      # Step 3: Build only if changes exist
      - name: Build ${{ matrix.project }}
        if: steps.check_project.outputs.changed == 'true'
        run: |            
            docker run --rm \
            -v ${{ github.workspace }}:/project \
            ghcr.io/masonedw/fa-xc32:latest \
            /bin/sh -c "/opt/microchip/mplabx/v5.45/mplab_platform/bin/prjMakefilesGenerator.sh Firmware/projects/${{ matrix.project }}/firmware/${{ matrix.project }}.X && \
                        make -C Firmware/projects/${{ matrix.project }}/firmware/${{ matrix.project }}.X/ build"
